com.fasterxml.jackson.*:* = 2.21.0
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.google.guava:guava = 33.5.0-jre
org.assertj:assertj-core = 3.27.7
org.junit.jupiter:* = 6.0.3
org.junit.platform:* = 6.0.3
org.slf4j:* = 2.0.17
com.palantir.safe-logging:* = 3.11.0
com.palantir.conjure:conjure = 4.54.0
com.palantir.conjure.java:* = 8.70.0
one.util:streamex = 0.8.4
org.mockito:* = 5.21.0
