com.fasterxml.jackson.*:* = 2.21.4
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.google.guava:guava = 33.6.0-jre
org.assertj:assertj-core = 3.27.7
org.junit.jupiter:* = 6.1.0
org.junit.platform:* = 6.1.0
ch.qos.logback:* = 1.5.18
org.slf4j:* = 2.0.17
com.palantir.safe-logging:* = 3.16.0
com.palantir.conjure:conjure = 4.59.0
com.palantir.conjure.java:* = 8.80.0
one.util:streamex = 0.8.4
org.mockito:* = 5.23.0
