dependencies {
    implementation 'com.google.guava:guava'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.4'
    implementation 'com.palantir.safe-logging:logger'
    implementation 'com.palantir.safe-logging:preconditions'
    implementation project(':lib-api:lib-api-objects')
    implementation 'one.util:streamex'

    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter'
}
